services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    ports:
      - 5435:${POSTGRES_PORT}
    networks:
      - kodemy
    deploy:
      replicas: 1

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_vol:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - kodemy
    deploy:
      replicas: 1

  opensearch:
    image: opensearchproject/opensearch:2.15.0
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1024m -Xmx1024m"
      cluster.name: kodemy-os-cluster
      node.name: kodemy-os-n1
      discovery.seed_hosts: kodemy-os-n1
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      bootstrap.memory_lock: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch_vol:/usr/share/opensearch/data
      #- ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    networks:
      - kodemy

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.15.0
    environment:
      OPENSEARCH_HOSTS: ${OPENSEARCH_HOSTS}
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
      #ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      #ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
    ports:
      - "5601:5601"
    networks:
      - kodemy
    depends_on:
      - opensearch

  redis:
    image: redis:latest
    volumes:
      - redis_vol:/data
    networks:
      - kodemy
    deploy:
      replicas: 1

  kodemy-api-gateway:
    image: kodemy-api-gateway:latest
    ports:
      - "8080:8080"
    networks:
      - kodemy
    environment:
      FRONTEND_PUBLIC_HOST: ${FRONTEND_PUBLIC_HOST}
    deploy:
      replicas: 1

  kodemy-auth:
    image: kodemy-auth:latest
    networks:
      - kodemy
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}?currentSchema=kodemy-auth
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      FRONTEND_PUBLIC_HOST: ${FRONTEND_PUBLIC_HOST}
      GATEWAY_PUBLIC_HOST: ${GATEWAY_PUBLIC_HOST}
    deploy:
      replicas: 1
    depends_on:
      - postgres
      - redis

  kodemy-backend:
    image: kodemy-backend:latest
    networks:
      - kodemy
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}?currentSchema=kodemy-backend
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
    deploy:
      replicas: 1
    depends_on:
      - postgres
      - rabbitmq

  kodemy-search:
    image: kodemy-search:latest
    networks:
      - kodemy
    environment:
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
    deploy:
      replicas: 1
    depends_on:
      - opensearch
      - rabbitmq

networks:
  kodemy:

volumes:
  postgres_vol:
    driver: local
  rabbitmq_vol:
    driver: local
  opensearch_vol:
    driver: local
  redis_vol:
    driver: local
