services:
  kodemy-service-registry:
    image: kodemy-service-registry:latest
    build:
      context: ./kodemy-service-registry
      dockerfile: ./Dockerfile
    networks:
      - kodemy
    deploy:
      replicas: 1

  kodemy-api-gateway:
    image: kodemy-api-gateway:latest
    build:
      context: ./kodemy-api-gateway
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - kodemy
    environment:
      FRONTEND_PUBLIC_HOST: ${FRONTEND_PUBLIC_HOST}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      OAUTH_GITHUB_ID: ${OAUTH_GITHUB_ID}
      OAUTH_GITHUB_KEY: ${OAUTH_GITHUB_KEY}
      EUREKA_URL: ${EUREKA_URL}
    deploy:
      replicas: 1
    depends_on:
      - kodemy-service-registry

  kodemy-auth:
    image: kodemy-auth:latest
    build:
      context: ./kodemy-auth
      dockerfile: ./Dockerfile
    networks:
      - kodemy
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      FRONTEND_PUBLIC_HOST: ${FRONTEND_PUBLIC_HOST}
      GATEWAY_PUBLIC_HOST: ${GATEWAY_PUBLIC_HOST}
      EUREKA_URL: ${EUREKA_URL}
      OAUTH_GITHUB_ID: ${OAUTH_GITHUB_ID}
      OAUTH_GITHUB_KEY: ${OAUTH_GITHUB_KEY}
      JWT_KEY: ${JWT_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    deploy:
      replicas: 1
    depends_on:
      - kodemy-service-registry

  kodemy-backend:
    image: kodemy-backend:latest
    build:
      context: ./kodemy-backend
      dockerfile: ./Dockerfile
    networks:
      - kodemy
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      EUREKA_URL: ${EUREKA_URL}
      JWT_KEY: ${JWT_KEY}
    deploy:
      replicas: 1

  kodemy-notification:
    image: kodemy-notification:latest
    build:
      context: ./kodemy-notification
      dockerfile: ./Dockerfile
    networks:
      - kodemy
    environment:
      SPRING_DATASOURCE_URL: ${DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      EUREKA_URL: ${EUREKA_URL}
    deploy:
      replicas: 1

  kodemy-search:
    image: kodemy-search:latest
    build:
      context: ./kodemy-search
      dockerfile: ./Dockerfile
    networks:
      - kodemy
    environment:
      SPRING_RABBITMQ_HOST: ${RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      EUREKA_URL: ${EUREKA_URL}
      JWT_KEY: ${JWT_KEY}
    deploy:
      replicas: 1

networks:
  kodemy:
    driver: bridge