services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kodemy
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - kodemy
    deploy:
      replicas: 1

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - rabbitmq_vol:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - kodemy
    deploy:
      replicas: 1

  opensearch:
    image: opensearchproject/opensearch:2.15.0
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1024m -Xmx1024m"
      cluster.name: kodemy-os-cluster
      node.name: kodemy-os-n1
      discovery.seed_hosts: kodemy-os-n1
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      bootstrap.memory_lock: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch_vol:/usr/share/opensearch/data
    networks:
      - kodemy
    deploy:
      replicas: 1

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.15.0
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    ports:
      - "5601:5601"
    networks:
      - kodemy
    deploy:
      replicas: 1
    depends_on:
      - opensearch

  redis:
    image: redis:latest
    volumes:
      - redis_vol:/data
    networks:
      - kodemy
    deploy:
      replicas: 1

  kodemy-api-gateway:
    image: kodemy-api-gateway:1.0
    ports:
      - "8080:8080"
    networks:
      - kodemy
    deploy:
      replicas: 3

  kodemy-auth:
    image: kodemy-auth:1.1
    networks:
      - kodemy
    deploy:
      replicas: 2
    depends_on:
      - postgres
      - redis

  kodemy-backend:
    image: kodemy-backend:1.0
    networks:
      - kodemy
    deploy:
      replicas: 2
    depends_on:
      - postgres
      - rabbitmq

  kodemy-search:
    image: kodemy-search:1.0
    networks:
      - kodemy
    deploy:
      replicas: 3
    depends_on:
      - opensearch
      - rabbitmq
      - opensearch-dashboards

networks:
  kodemy:

volumes:
  postgres_vol:
    driver: local
  rabbitmq_vol:
    driver: local
  opensearch_vol:
    driver: local
  redis_vol:
    driver: local