services:
  postgres:
    env_file:
      - .env
    environment:
    deploy:
      replicas: 1

  rabbitmq:
    env_file:
      - .env
    environment:
    deploy:
      replicas: 1

  opensearch:
    env_file:
      - .env
    environment:
      cluster.name: kodemy-os-cluster
      node.name: kodemy-os-n1
      discovery.seed_hosts: kodemy-os-n1
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      bootstrap.memory_lock: "true"
    volumes:
      - opensearch_vol:/usr/share/opensearch/data
      #- ./config/opensearch-security:/usr/share/opensearch/config/opensearch-security
      #- ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ulimits:
    deploy:
      replicas: 1

  opensearch-dashboards:
    env_file:
      - .env
    deploy:
      replicas: 1

  redis:
    deploy:
      replicas: 1