services:
  postgres:
    image: postgres:14.1-alpine
    container_name: kodemy_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER]
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    networks:
      - kodemy

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: kodemy_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_vol:/var/lib/rabbitmq
    networks:
      - kodemy

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: kodemy_opensearch
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1024m -Xmx1024m"
      cluster.name: kodemy-os-cluster
      node.name: kodemy-os-n1
      discovery.seed_hosts: kodemy-os-n1
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      bootstrap.memory_lock: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch_vol:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - kodemy

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: kodemy_opensearch-dashboards
    environment:
      OPENSEARCH_HOSTS: ${OPENSEARCH_HOSTS}
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
    ports:
      - "5601:5601"
    networks:
      - kodemy
    depends_on:
      - opensearch

  redis:
    image: redis:latest
    container_name: kodemy_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_vol:/data
    networks:
      - kodemy

networks:
  kodemy:

volumes:
  postgres_vol:
    driver: local
  rabbitmq_vol:
    driver: local
  opensearch_vol:
    driver: local
  redis_vol:
    driver: local