services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_vol:/var/lib/postgresql/data
      - ./init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - kodemy
    deploy:
      replicas: 1

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_vol:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - kodemy
    deploy:
      replicas: 1

  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      OPENSEARCH_JAVA_OPTS: "-Xms1024m -Xmx1024m"
      cluster.name: kodemy-os-cluster
      node.name: kodemy-os-n1
      discovery.seed_hosts: kodemy-os-n1
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      bootstrap.memory_lock: "true"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    #   nofile:
    #     soft: 65536
    #     hard: 65536
    volumes:
      - opensearch_vol:/usr/share/opensearch/data
      #- ./config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - kodemy

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    environment:
      OPENSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS}
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
      #ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      #ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
    ports:
      - "5601:5601"
    networks:
      - kodemy
    depends_on:
      - opensearch

  redis:
    image: redis:latest
    volumes:
      - redis_vol:/data
    networks:
      - kodemy
    deploy:
      replicas: 1

networks:
  kodemy:

volumes:
  postgres_vol:
    driver: local
  rabbitmq_vol:
    driver: local
  opensearch_vol:
    driver: local
  redis_vol:
    driver: local
