version: '3'

services:
  app:
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - lan
    depends_on:
      - postgredb

  postgredb:
    image: postgres
    container_name: kodemy_db
    restart: always
    environment:
      - POSTGRES_USER=kodemy_usr
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kodemy
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - lan

networks:
  lan:
    driver: bridge

volumes:
  postgresql: