version: '3.7'

services:
  api:
    build: .
    container_name: kodemy_api_dev
    profiles:
      - test
    restart: unless-stopped
    ports:
      - "8181:8080"
    networks:
      - lan
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    container_name: kodemy_postgres_dev
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kodemy
    ports:
      - "5435:5432"
    restart: always
    volumes:
      - postgres_dev:/var/lib/postgresql/data
      - ./sql:/sql
    networks:
      - lan

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: kodemy_rabbitmq_dev
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_dev:/var/lib/rabbitmq
    networks:
      - lan


networks:
  lan:
    driver: bridge

volumes:
  postgres_dev:
  rabbitmq_dev: