spring:
  application.name: kodemy-auth
  banner.location: classpath:banner.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres/kodemy?currentSchema=kodemy-auth
    username: postgres
    password: postgres
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate.ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate.types.print.banner: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-root.xml
    contexts: prod
    enabled: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23liqWT50Vtt0A0uIg
            clientSecret: 8d3b1c72e34f2077e433c46f0aea4b980c15226b
            redirect-uri: ${app.security.oauth2.route.gateway}${app.security.oauth2.endpoints.callback}/github
            scope: ['user:email', 'read:user']

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: when_authorized
      roles: CAN_USE_ACTUATOR
      show-components: always
  server:
    port: 9000

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  filter:
    enabled: true
  predicate:
    exclude:
      - path: /swagger-ui/**
        methods: "*"
      - path: /actuator/info
        methods: "*"
      - path: /actuator/health
        methods: "*"

network:
  route:
    gateway: http://kodemy-api-gateway:8080

jwt:
  secret-key: YWJjZGVmZ2hjvbwjrW5vcHFyc3R1dnd4eXoxMjM0NTY3OnDMTIzNDU2Nzg5MDEyMzQ1Njc4OTAf=

app:
  security:
    cors:
      credentials: true
      mapping: "/**"
    oauth2:
      route:
        front: ${FRONTEND_PUBLIC_HOST}
        gateway: ${GATEWAY_PUBLIC_HOST}
      endpoints:
        authorize: /api/oauth2/authorize
        callback: /api/oauth2/callback
        redirect: /api/callback
    roles:
      primary: ROLE_USER