server.port: 8081

spring:
  application.name: kodemy-auth
  banner.location: classpath:banner.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres/kodemy?currentSchema=kodemy-auth
    username: postgres
    password: postgres
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate.ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate.types.print.banner: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-root.xml
    contexts: prod
    enabled: true
  security:
    oauth2:
      path:
        authorize: /api/oauth2/authorize
        callback: /api/oauth2/callback
        error: /
      client:
        registration:
          github:
            clientId: Ov23liqWT50Vtt0A0uIg
            clientSecret: 8d3b1c72e34f2077e433c46f0aea4b980c15226b
            redirect-uri: ${app.security.oauth2.route.redirect}${app.security.oauth2.endpoints.callback}/github
            scope: ['user:email', 'read:user']

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: when_authorized
      roles: CAN_USE_ACTUATOR
      show-components: always

network:
  route:
    front: /
    gateway: http://kodemy-api-gateway:8080
    backend: http://kodemy-backend:8080
    search: http://kodemy-search:8080

jwt:
  secret-key: YWJjZGVmZ2hjvbwjrW5vcHFyc3R1dnd4eXoxMjM0NTY3OnDMTIzNDU2Nzg5MDEyMzQ1Njc4OTAf=

app:
  security:
    cors:
      credentials: true
      mapping: "/**"
    oauth2:
      route:
        redirect: ${APP_SECURITY_OAUTH2_ROUTE_REDIRECT:${network.route.gateway}}
      endpoints:
        authorize: /api/oauth2/authorize
        callback: /api/oauth2/callback
    roles:
      primary: ROLE_USER
      authorities:
        ROLE_MODERATOR:
          - CAN_MODIFY_TAGS
          - CAN_APPROVED_MATERIAL
          - CAN_GET_USER_INFO
          - CAN_VIEW_ALL_MATERIALS
          - CAN_DEPRECATE_MATERIAL
        ROLE_ADMIN:
          - CAN_MODIFY_TAGS
          - CAN_APPROVED_MATERIAL
          - CAN_AUTO_APPROVED_MATERIAL
          - CAN_GET_USERS
          - CAN_BANNING_USERS
          - CAN_ASSIGN_ROLES
          - CAN_GET_USER_INFO
          - CAN_READ_NOTIFICATIONS
          - CAN_INDEX
          - CAN_VIEW_ALL_MATERIALS
          - CAN_DEPRECATE_MATERIAL
        ROLE_SUPERADMIN:
          - CAN_MODIFY_TAGS
          - CAN_APPROVED_MATERIAL
          - CAN_AUTO_APPROVED_MATERIAL
          - CAN_GET_USERS
          - CAN_BANNING_USERS
          - CAN_ASSIGN_ROLES
          - CAN_USE_ACTUATOR
          - CAN_GET_USER_INFO
          - CAN_READ_NOTIFICATIONS
          - CAN_INDEX
          - CAN_VIEW_ALL_MATERIALS
          - CAN_DEPRECATE_MATERIAL
          - CAN_BAN_MATERIAL
          - CAN_UNBAN_MATERIAL