spring:
  data:
    redis:
      host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5435/kodemy?currentSchema=kodemy-auth

app:
  opensearch:
    host: http://localhost:9200
  security:
    cors:
      allowed-origins:
        - http://localhost:3000
      credentials: true
      mapping: "/**"
