server.port: 8081

spring:
  application.name: kodemy-auth
  banner.location: classpath:banner.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres/kodemy?currentSchema=kodemy-auth
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate.ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate.types.print.banner: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-root.xml
    contexts: prod
    enabled: true
  security:
    oauth2:
      path:
        authorize: /api/oauth2/authorize
        callback: /api/oauth2/callback
        error: /
      client:
        registration:
          github:
            clientId: Ov23liqWT50Vtt0A0uIg
            clientSecret: 8d3b1c72e34f2077e433c46f0aea4b980c15226b
            redirect-uri: ${routes.gateway}${spring.security.oauth2.path.callback}/github
            scope:
              - user:email
              - read:user

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: when_authorized
      roles: CAN_USE_ACTUATOR
      show-components: always

network:
  routes:
    front: /
    backend: http://localhost:8082
    search: http://localhost:8083
  databus:
    username: user
    password: password
    connect-timeout-ms: 3000
    read-timeout-ms: 5000

jwt:
  secret-key: YWJjZGVmZ2hjvbwjrW5vcHFyc3R1dnd4eXoxMjM0NTY3OnDMTIzNDU2Nzg5MDEyMzQ1Njc4OTAf=

app:
  opensearch:
    host: opensearch
    index:
      name: materials
      alias: materials-alias
  security:
    cors:
      allowed-origins:
        - http://localhost:3000
      credentials: true
      mapping: "/**"
    roles:
      primary: ROLE_USER
      authorities:
        ROLE_MODERATOR:
          - CAN_MODIFY_TAGS
          - CAN_APPROVED_MATERIAL
          - CAN_GET_USER_INFO
          - CAN_VIEW_ALL_MATERIALS
          - CAN_DEPRECATE_MATERIAL
        ROLE_ADMIN:
          - CAN_MODIFY_TAGS
          - CAN_APPROVED_MATERIAL
          - CAN_AUTO_APPROVED_MATERIAL
          - CAN_GET_USERS
          - CAN_BANNING_USERS
          - CAN_ASSIGN_ROLES
          - CAN_GET_USER_INFO
          - CAN_READ_NOTIFICATIONS
          - CAN_INDEX
          - CAN_VIEW_ALL_MATERIALS
          - CAN_DEPRECATE_MATERIAL
        ROLE_SUPERADMIN:
          - CAN_MODIFY_TAGS
          - CAN_APPROVED_MATERIAL
          - CAN_AUTO_APPROVED_MATERIAL
          - CAN_GET_USERS
          - CAN_BANNING_USERS
          - CAN_ASSIGN_ROLES
          - CAN_USE_ACTUATOR
          - CAN_GET_USER_INFO
          - CAN_READ_NOTIFICATIONS
          - CAN_INDEX
          - CAN_VIEW_ALL_MATERIALS
          - CAN_DEPRECATE_MATERIAL
          - CAN_BAN_MATERIAL
          - CAN_UNBAN_MATERIAL