server.port: 8081

spring:
  data:
    redis:
      host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5435/kodemy?currentSchema=kodemy-auth

management:
  server:
    port: ${server.port}

logbook:
  obfuscate:
    headers:
      - Authorization

network:
  route:
    gateway: http://localhost:8080

jwt:
  bearer:
    expiration-min: 720

app:
  security:
    oauth2:
      route:
        front: http://localhost:3000
        gateway: ${network.route.gateway}
