spring:
  data:
    redis:
      host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5435/kodemy?currentSchema=kodemy-auth

logbook:
  obfuscate:
    headers:
      - Authorization

network:
  route:
    gateway: http://localhost:8080

jwt:
  bearer:
    expiration-min: 720

app:
  security:
    cors:
      allowed-origins: "*"
      credentials: false
      mapping: "/**"
    oauth2:
      route:
        redirect: http://localhost:3000


