spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kodemy
    username: kodemy_usr
    password:
  jpa:
    show-sql: true
  liquibase:
    contexts: dev
  security:
    user:
      name: admin
      password: admin