server:
  port: 8181

spring:
  datasource:
    host-port: localhost:5435
  liquibase:
    contexts: local
  rabbitmq:
    host: localhost
    port: 5672

logging:
  level:
    org.springframework.security: DEBUG