spring:
  banner:
    location: classpath:banner.txt
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-root.xml
  sql:
    init:
      mode: never