server.port: 8080

spring:
  application.name: kodemy-gateway
  banner.location: classpath:banner.txt
  cloud.gateway.routes:
    -
      id: kodemy-auth-any-any
      uri: ${app.service.auth}
      predicates:
        - Path=/api/users/**,/api/roles,/api/oauth2/**
      filters:
        - GatewayAuthFilter
    -
      id: kodemy-backend-admin-any
      uri: ${app.service.backend}
      predicates:
        - Path=/api/admin/**
      filters:
        - GatewayAuthFilter
    -
      id: kodemy-backend-materials-id-get
      uri: ${app.service.backend}
      predicates:
        - Path=/api/materials/{materialId}/**
        - Method=GET
      filters:
        - AuthFilter
    -
      id: kodemy-backend-materials-post
      uri: ${app.service.backend}
      predicates:
        - Path=/api/materials
        - Method=POST
      filters:
        - GatewayAuthFilter
    -
      id: kodemy-backend-any-any
      uri: ${app.service.backend}
      predicates:
        - Path=/api/technologies,/api/types,/api/sections,/api/categories/{categoryId}
      filters:
        - GatewayAuthFilter
    -
      id: kodemy-search-any-any
      uri: ${app.service.search}
      predicates:
        - Path=/api/materials
        - Method=GET
      filters:
        - GatewayAuthFilter

app:
  service:
    host-uri: http://localhost
    auth: ${app.service.host-uri}:8081
    backend: ${app.service.host-uri}:8082
    search: ${app.service.host-uri}:8083
