spring:
  datasource.url: jdbc:postgresql://localhost:5435/kodemy?currentSchema=kodemy-backend
  jpa.show-sql: true
  liquibase.contexts: dev,local
  rabbitmq:
    host: localhost

logging.level:
  org.springframework.security: DEBUG

kodemy:
  jwt:
    expiration-mins: 60
  security:
    cors:
      allowedUris:
        - http://localhost:3000