server.port: 8082

spring:
  application.name: kodemy-backend
  banner.location: classpath:banner.txt
  cloud:
    function:
      definition: test
    stream:
      bindings:
        materialCreated-out-0:
          destination: material-created
        materialUpdated-out-0:
          destination: material-updated
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres/kodemy?currentSchema=kodemy-backend
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate.ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate.types.print.banner: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-root.xml
    contexts: prod
    enabled: true
  rabbitmq:
    host: rabbitmq
    username: rabbitmq
    password: rabbitmq
    port: 5672

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: always
      roles: CAN_USE_ACTUATOR
      show-components: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0

network:
  routes:
    front: /
    auth: http://localhost:8081
    search: http://localhost:8083
  databus:
    username: user
    password: password
    connect-timeout-ms: 3000
    read-timeout-ms: 5000

jwt:
  secret-key: YWJjZGVmZ2hjvbwjrW5vcHFyc3R1dnd4eXoxMjM0NTY3OnDMTIzNDU2Nzg5MDEyMzQ1Njc4OTAf=