spring:
  datasource.url: jdbc:postgresql://localhost:5435/kodemy?currentSchema=kodemy-backend
  jpa.show-sql: true
  liquibase.contexts: dev,local
  rabbitmq:
    host: localhost

management:
  server:
    port: ${server.port}

logging.level:
  org.springframework.security: DEBUG

jwt:
  expiration-mins: 60