server.port: 8082

spring:
  application.name: kodemy-backend
  banner.location: classpath:banner.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres/kodemy?currentSchema=kodemy-backend
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate.ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate.types.print.banner: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-root.xml
    contexts: prod
    enabled: true
  rabbitmq:
    host: postgres
    username: rabbitmq
    password: rabbitmq
    port: 5671

kodemy:
  rabbit:
    queues:
      m-created:
        name: material.created
      m-updated:
        name: material.updated
      notification:
        name: notification