spring:
  datasource.url: jdbc:postgresql://localhost:5435/kodemy?currentSchema=kodemy-notification
  jpa.show-sql: true
  liquibase.contexts: dev,local
  rabbitmq:
    host: localhost

logging.level:
    org.springframework.security: DEBUG