spring:
  application.name: kodemy-api-gateway
  banner.location: classpath:banner.txt
  cloud:
    gateway:
      routes:
        - id: oauth2_auth
          uri: ${network.route.auth}
          predicates:
            - Path=/api/oauth2/**,/api/auth/**,/api/logout

        - id: search-materials
          uri: ${network.route.search}
          predicates:
            - Path=/api/materials
            - Method=GET

        - id: materials-get
          uri: ${network.route.backend}
          predicates:
            - Path=/api/materials/{materialId}/**
            - Method=GET

        - id: materials-post
          uri: ${network.route.backend}
          predicates:
            - Path=/api/materials
            - Method=POST

        - id: users-materials
          uri: ${network.route.auth}
          predicates:
            - Path=/api/users/{userId}/materials

        - id: users_roles
          uri: ${network.route.auth}
          predicates:
            - Path=/api/users/**,/api/roles

        - id: tags_types_sections_categories_admin
          uri: ${network.route.backend}
          predicates:
            - Path=/api/tags,/api/types,/api/sections,/api/categories/{categoryId},/api/admin/**

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always
      roles: CAN_USE_ACTUATOR
      show-components: always
  server:
    port: 9000

network:
  route:
    front: ${FRONTEND_PUBLIC_HOST}
    auth: http://kodemy-auth:8080
    backend: http://kodemy-backend:8080
    search: http://kodemy-search:8080

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
    org.springframework.cloud.gateway: trace

app:
  security:
    cors:
      allowed-origins:
        - ${network.route.front}