server:
  port: 8080

management:
  server:
    port: ${server.port}

network:
  route:
    front: http://localhost:3000
    auth: http://localhost:8081
    backend: http://localhost:8082
    search: http://localhost:8083

app:
  security:
    cors:
      allowed-origins:
        - ${network.route.front}