spring:
  application.name: kodemy-api-gateway
  banner.location: classpath:banner.txt
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: auth_logout
          uri: ${service.baseUrl.auth}
          predicates:
            - Path=/api/auth/logout
          filters:
            - Logout

        - id: oauth2_auth
          uri: ${service.baseUrl.auth}
          predicates:
            - Path=/api/oauth2/**,/api/auth/**

        - id: search-materials
          uri: ${service.baseUrl.search}
          predicates:
            - Path=/api/materials
            - Method=GET

        - id: materials-get
          uri: ${service.baseUrl.backend}
          predicates:
            - Path=/api/materials/{materialId}/**
            - Method=GET

        - id: materials-post
          uri: ${service.baseUrl.backend}
          predicates:
            - Path=/api/materials
            - Method=POST

        - id: materials-grades
          uri: ${service.baseUrl.backend}
          predicates:
            - Path=/api/materials/{materialId}/grades
            - Method=POST

        - id: users-materials
          uri: ${service.baseUrl.auth}
          predicates:
            - Path=/api/users/{userId}/materials

        - id: users_roles
          uri: ${service.baseUrl.auth}
          predicates:
            - Path=/api/users/**,/api/roles

        - id: tags_types_sections_categories_admin
          uri: ${service.baseUrl.backend}
          predicates:
            - Path=/api/tags,/api/types,/api/sections,/api/categories/{categoryId},/api/admin/**
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23li5LD47i4815okXp
            clientSecret: fd2972bffedc3ad0e0a9eeda2935e4ac0255c70a
            redirect-uri: "{baseUrl}${app.security.oauth2.endpoint.callback}/github"
            scope: [ 'user:email', 'read:user' ]

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always
      roles: CAN_USE_ACTUATOR
      show-components: always
  server:
    port: 9000

service:
  baseUrl:
    auth: http://kodemy-auth:8080
    backend: http://kodemy-backend:8080
    search: http://kodemy-search:8080
    front: ${FRONTEND_PUBLIC_HOST}
  uri:
    exchangeCode: ${service.baseUrl.auth}${app.security.oauth2.endpoint.authorize}/{id}
    refreshAccessToken: ${service.baseUrl.auth}/api/auth/access_token

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
    org.springframework.cloud.gateway: trace

app:
  security:
    cors:
      allowed-origins:
        - ${service.baseUrl.front}
    cookie:
      access-token-age: 720
      refresh-token-age: 1440
    oauth2:
      endpoint:
        authorize: /api/oauth2/authorize
        callback: /api/oauth2/callback
        redirect: /api/callback

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}