spring:
  application.name: kodemy-api-gateway
  banner.location: classpath:banner.txt
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://kodemy-auth
          predicates:
            - Path=/api/auth/**,/api/users/**,/api/roles/**
        - id: notification
          uri: lb://kodemy-notification
          predicates:
            - Path=/api/notification/**
        - id: search
          uri: lb://kodemy-search
          predicates:
            - Path=/api/search/**
        - id: oauth2_auth
          uri: ${network.route.auth}
          predicates:
            - Path=/api/oauth2/**,/api/auth/**,/api/logout
        - id: backend
          uri: lb://kodemy-backend
          predicates:
            - Path=/api/**

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always
      roles: CAN_USE_ACTUATOR
      show-components: always
  server:
    port: 9000

network:
  route:
    auth: http://kodemy-auth:8080
    backend: http://kodemy-backend:8080
    search: http://kodemy-search:8080

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
    org.springframework.cloud.gateway: trace

app:
  security:
    cors:
      allowed-origins:
        - ${network.route.front}