spring:
  application.name: kodemy-api-gateway
  banner.location: classpath:banner.txt
  cloud:
    gateway:
      routes:
        - id: oauth2_callback
          uri: ${service.baseUrl.auth}
          predicates:
            - Path=${app.security.oauth2.endpoint.callback}/{provider}
          filters:
            - RewritePath=${app.security.oauth2.endpoint.callback}/(?<provider>.*), ${app.security.oauth2.endpoint.authorize}/${provider}
            - name: FrontendRedirect
              args:
                location: ${service.baseUrl.front}
            - RewriteCookieToBearer

        - id: auth_logout
          uri: ${service.baseUrl.auth}
          predicates:
            - Path=/api/auth/logout
          filters:
            - RewriteCookieToBearer
            - Logout

        - id: oauth2_auth
          uri: ${service.baseUrl.auth}
          predicates:
            - Path=/api/oauth2/**,/api/auth/**
          filters:
            - RewriteCookieToBearer

        - id: search-materials
          uri: ${service.baseUrl.search}
          predicates:
            - Path=/api/materials
            - Method=GET

        - id: materials-get
          uri: ${service.baseUrl.backend}
          predicates:
            - Path=/api/materials/{materialId}/**
            - Method=GET
          filters:
            - RewriteCookieToBearer

        - id: materials-post
          uri: ${service.baseUrl.backend}
          predicates:
            - Path=/api/materials
            - Method=POST
          filters:
            - RewriteCookieToBearer

        - id: materials-grades
          uri: ${service.baseUrl.backend}
          predicates:
            - Path=/api/materials/{materialId}/grades
            - Method=POST
          filters:
            - RewriteCookieToBearer

        - id: users-materials
          uri: ${service.baseUrl.auth}
          predicates:
            - Path=/api/users/{userId}/materials
          filters:
            - RewriteCookieToBearer

        - id: users_roles
          uri: ${service.baseUrl.auth}
          predicates:
            - Path=/api/users/**,/api/roles
          filters:
            - RewriteCookieToBearer

        - id: tags_types_sections_categories_admin
          uri: ${service.baseUrl.backend}
          predicates:
            - Path=/api/tags,/api/types,/api/sections,/api/categories/{categoryId},/api/admin/**
          filters:
            - RewriteCookieToBearer
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${OAUTH_GITHUB_ID}
            clientSecret: ${OAUTH_GITHUB_KEY}
            redirect-uri: "{baseUrl}${app.security.oauth2.endpoint.callback}/github"
            scope: [ 'user:email', 'read:user' ]

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always
      roles: CAN_USE_ACTUATOR
      show-components: always
  server:
    port: 9000

service:
  baseUrl:
    auth: http://kodemy-auth:8080
    backend: http://kodemy-backend:8080
    search: http://kodemy-search:8080
    front: ${FRONTEND_PUBLIC_HOST}

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
    org.springframework.cloud.gateway: trace

app:
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:[]}
    oauth2:
      endpoint:
        authorize: /api/oauth2/authorize
        callback: /api/oauth2/callback
        redirect: /api/callback

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}