server.port: 8083

spring:
  application.name: kodemy-search
  banner.location: classpath:banner.txt
  cloud:
    function:
      definition: materialCreated;materialUpdated
    stream:
      default-binder: rabbit
      bindings:
        materialCreated-in-0:
          content-type: application/json
          destination: material-created
          group: kodemy
        materialUpdated-in-0:
          content-type: application/json
          destination: material-updated
          group: kodemy
      rabbit:
        bindings:
          materialCreated-in-0:
            consumer:
              auto-bind-dlq: true
              dead-letter-exchange:
              max-length: 3
          materialUpdated-in-0:
            consumer:
              auto-bind-dlq: true
              dead-letter-exchange:
              max-length: 3
  rabbitmq:
    host: rabbitmq
    username: rabbitmq
    password: rabbitmq
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /api/actuator
  endpoint:
    health:
      show-details: when_authorized
      roles: CAN_USE_ACTUATOR
      show-components: always

jwt:
  secret-key: P8K53KMRFBWDRH3EBWYV3B9MQG6QU8V59PYRWGDG96MNDCYBQCJ5EEGXT5ZF76E6

opensearch:
  host: opensearch
  indices:
    materials:
      name: materials
      alias: materials-alias

app:
  rabbit:
    queues:
      m-created:
        name: material.created
        exchange: direct
      m-updated:
        name: material.updated
        exchange: direct
  security:
    cors:
      allowed-origins:
        - http://localhost:3000
      credentials: true
      mapping: "/**"
