server.port: 8083

spring:
  rabbitmq:
    host: localhost

management:
  server:
    port: ${server.port}

logging:
  level:
    org.springframework.security: DEBUG

app:
  security:
    jwt:
      secret-key: P8K53KMRFBWDRH3EBWYV3B9MQG6QU8V59PYRWGDG96MNDCYBQCJ5EEGXT5ZF76E6

opensearch:
  host: http://localhost:9200

eureka:
  client:
    enabled: false