spring:
  rabbitmq:
    host: localhost

kodemy:
  jwt:
    expiration-mins: 60
  opensearch:
    host: http://localhost:9200
  security:
    cors:
      allowed-uris:
        - http://localhost:3000

logging.level:
  org.springframework.security: DEBUG
