server.port: 8083

spring:
  application.name: kodemy-search
  banner.location: classpath:banner.txt
  rabbitmq:
    host: rabbitmq
    username: rabbitmq
    password: rabbitmq
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /api/actuator
  endpoint:
    health:
      show-details: when_authorized
      roles: CAN_USE_ACTUATOR
      show-components: always

jwt:
  secret-key: P8K53KMRFBWDRH3EBWYV3B9MQG6QU8V59PYRWGDG96MNDCYBQCJ5EEGXT5ZF76E6

app:
  opensearch:
    host: opensearch
    index:
      name: materials
      alias: materials-alias
  rabbit:
    queues:
      m-created:
        name: material.created
        exchange: direct
      m-updated:
        name: material.updated
        exchange: direct
  security:
    auth:
      key:
        jwt: jwtsession