server:
  port: 8083

spring:
  rabbitmq:
    host: localhost

logging:
  level:
    org.springframework.security: DEBUG

opensearch:
  host: http://localhost:9200

app:
  security:
    cors:
      allowed-origins:
        - http://localhost:3000
      mapping: "/**"
      credentials: true
