server.port: 8083

spring:
  application.name: kodemy-search
  banner.location: classpath:banner.txt
  cloud:
    function:
      definition: materialCreated;materialUpdated;materialStatusUpdated
    stream:
      default-binder: rabbit
      bindings:
        materialCreated-in-0:
          contentType: application/json
          destination: material-created
          group: kodemy
        materialUpdated-in-0:
          contentType: application/json
          destination: material-updated
          group: kodemy
        materialStatusUpdated-in-0:
          contentType: application/json
          destination: material-status-updated
          group: kodemy
        materialTagsUpdated-in-0:
          contentType: application/json
          destination: material-tags-updated
          group: kodemy
      rabbit:
        bindings:
          materialCreated-in-0:
            consumer:
              auto-bind-dlq: true
              dlqTtl: 5000
              dlqDeadLetterExchange:
              maxLength: 3
          materialUpdated-in-0:
            consumer:
              auto-bind-dlq: true
              dlqTtl: 5000
              dlqDeadLetterExchange:
              maxLength: 3
          materialStatusUpdated-in-0:
            consumer:
              auto-bind-dlq: true
              dlqTtl: 5000
              dlqDeadLetterExchange:
              maxLength: 3
          materialTagsUpdated-in-0:
            consumer:
              auto-bind-dlq: true
              dlqTtl: 5000
              dlqDeadLetterExchange:
              maxLength: 3
  rabbitmq:
    host: rabbitmq
    username: rabbitmq
    password: rabbitmq
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /api/actuator
  endpoint:
    health:
      show-details: when_authorized
      roles: CAN_USE_ACTUATOR
      show-components: always

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  filter:
    enabled: true
  predicate:
    exclude:
      - path: /swagger-ui/**
        methods: "*"
      - path: /actuator/info
        methods: "*"
      - path: /actuator/health
        methods: "*"

jwt:
  secret-key: P8K53KMRFBWDRH3EBWYV3B9MQG6QU8V59PYRWGDG96MNDCYBQCJ5EEGXT5ZF76E6

opensearch:
  host: http://opensearch:9200
  indices:
    materials:
      name: materials
      alias: materials-alias
  username: admin
  password: admin
