spring:
  rabbitmq:
    host: localhost

logging.level:
  org.springframework.security: DEBUG

jwt:
  expiration-mins: 60

app:
  opensearch:
    host: http://localhost:9200
  security:
    cors:
      allowed-uris:
        - http://localhost:3000
