server:
  port: 8083

spring:
  rabbitmq:
    host: localhost

management:
  server:
    port: ${server.port}

logging:
  level:
    org.springframework.security: DEBUG

opensearch:
  host: http://localhost:9200
