spring:
  datasource:
    url: jdbc:h2:mem:kodemy
    username: kodemy_usr
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  liquibase:
    contexts: dev
  security:
    user:
      name: admin
      password: admin